# Generated by Django 2.0.5 on 2018-09-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('dFirstAppointment', models.DateField()),
                ('rank', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=30)),
                ('salaryGLevel', models.IntegerField(max_length=4)),
                ('step', models.IntegerField(max_length=5)),
                ('yLastPromotion', models.DateField()),
                ('pressentYear', models.DateField()),
                ('nYearsPresentG', models.IntegerField(max_length=3)),
                ('teachingE', models.IntegerField(max_length=3)),
                ('publicationS', models.IntegerField(max_length=3)),
                ('responsibilityS', models.IntegerField(max_length=3)),
                ('totalScore', models.IntegerField(max_length=3)),
                ('duePromotion', models.BooleanField()),
                ('systemRecomUpgrade', models.CharField(max_length=20)),
            ],
        ),
    ]
