# Generated by Django 2.0.5 on 2018-09-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_staff',
            name='nYearsPresentG',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='a_staff',
            name='publicationS',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='a_staff',
            name='responsibilityS',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='a_staff',
            name='salaryGLevel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='a_staff',
            name='step',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='a_staff',
            name='teachingE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='a_staff',
            name='totalScore',
            field=models.IntegerField(),
        ),
    ]
