# Generated by Django 2.1.1 on 2018-09-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0003_auto_20180910_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='None_A_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='staff name')),
                ('dFirstAppointment', models.DateField(verbose_name='Date of first appointment')),
                ('qualification', models.CharField(max_length=30, verbose_name='Top Qualification')),
                ('salaryGLevel', models.IntegerField(verbose_name='Salary grade Level')),
                ('step', models.IntegerField(verbose_name='Step')),
                ('yLastPromotion', models.DateField(verbose_name='Year of last promotion')),
                ('pressentYear', models.DateField(verbose_name='Present Year')),
                ('responsibilityS', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, verbose_name='Responsibility Score')),
                ('totalScore', models.IntegerField(verbose_name='Total score')),
                ('nYearsPresentG', models.IntegerField(blank=True, verbose_name='No of years on present grade')),
                ('duePromotion', models.BooleanField(verbose_name='Due Promotion')),
                ('systemRecomUpgrade', models.CharField(max_length=20, verbose_name='System Upgrade')),
                ('a_pcRecom', models.CharField(max_length=20, verbose_name='System Upgrade')),
            ],
            options={
                'verbose_name_plural': 'None Academic Staff Database',
                'ordering': ['name'],
            },
        ),
    ]
