# Generated by Django 2.1.1 on 2018-09-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0004_none_a_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='none_a_staff',
            name='a_pcRecom',
            field=models.CharField(max_length=20, verbose_name='A and PC recommendation'),
        ),
    ]
