# Generated by Django 2.1.1 on 2018-09-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0005_auto_20180912_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_staff',
            name='avater',
            field=models.FileField(blank=True, upload_to='picture', verbose_name='Profile image'),
        ),
        migrations.AddField(
            model_name='a_staff',
            name='faculty',
            field=models.CharField(choices=[('science', 'Medical science'), ('engineering', 'engineering')], default='science', max_length=30, verbose_name='Rank'),
        ),
        migrations.AddField(
            model_name='a_staff',
            name='pub',
            field=models.TextField(default='No publication yet', verbose_name='Publications in Previous Years e.g(books)'),
        ),
        migrations.AddField(
            model_name='none_a_staff',
            name='avater',
            field=models.FileField(blank=True, upload_to='picture', verbose_name='Profile image'),
        ),
    ]
